# Generated by Django 5.0.7 on 2024-07-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generated_image",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="generated_image",
            name="prompt",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="ImageURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "generated_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_urls",
                        to="generator_app.generated_image",
                    ),
                ),
            ],
        ),
    ]
