# Generated by Django 5.0.7 on 2024-07-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator_app", "0002_remove_generated_image_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generated_image",
            name="url",
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
