# Generated by Django 5.0.7 on 2024-07-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generator_app", "0003_generated_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generated_image",
            name="url",
        ),
    ]
