# Generated by Django 5.0.7 on 2024-07-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator_app", "0004_remove_generated_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="generated_image",
            name="image_url",
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="generated_image",
            name="prompt",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="ImageURL",
        ),
    ]
