# Generated by Django 5.0.7 on 2024-07-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generator_app", "0005_generated_image_image_url_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Generated_Image",
            new_name="GeneratedImage",
        ),
    ]
